### ISSUE TITLE
kirby-2.1.1 security update breaks kirbycms-extension-image

### ISSUE THREAD

**Issue by aagd** [fanningert/kirbycms-extension-image#16]
Parse error: syntax error, unexpected '[' in /Users/username/Sites/kirby/site/plugins/kirbycms-extension-image/kirbycms-extension-image-lib-block-object.php on line 88

Maybe a similar issue as with the video extension. I tried it with a clean new kirby install without extra plugins.

**Update:** The problem does occur only on PHP 5.3. On PHP 5.6 all works fine.

**Comment by fanningert** [comment]
Interesting. I will check it. Ok, this is a feature what is new at PHP 5.4.0.
http://php.net/manual/en/migration54.new-features.php

**Comment by aagd** [comment]
Mine was 5.3.29. Now on 5.6.12 the error is gone...

**Comment by fanningert** [comment]
@aagd Sorry, I updated my post.

**Comment by fanningert** [comment]
@aagd I made a little correction. Can you test it? https://github.com/fanningert/kirbycms-extension-image/commit/4f0d43e95ca073bcea0c0482a1c30cf789cfc555

**Comment by aagd** [comment]
Now it's `Parse error: syntax error, unexpected '[' in /Users/username/Sites/kirby/site/plugins/kirbycms-extension-image/kirbycms-extension-image-lib-block-object.php on line 217`

**Comment by fanningert** [comment]
Ok the some error on a other position. I think this will not the last position of the problem. I will correct the problem tomorrow.

**Comment by aagd** [comment]
Very cool, thanks!

**Comment by fanningert** [comment]
@aagd 
Can you test it. I updated the code for 5.3 support. I don't know if there is another one position with the same problem. I am not able to test it, because I have no machine with 5.3 at the moment. 5fa5958a7c9153eb295a7f17fb7dfba1e9883e50

**Comment by aagd** [comment]
Yes sure, I'll try this tomorrow. Have to leave now...

**Comment by aagd** [comment]
Looks good, error is gone.
