### ISSUE TITLE
Using methods directly in template

### ISSUE THREAD

**Issue by bravokiloecho** [fanningert/kirbycms-extension-image#17]
Is there a way to use the methods this plugin provides directly in the template rather than as KirbyTags in the panel?

Apologies if I'm missing something obvious here but I'm new to Kirby.

This is a really great looking plugin and I'm looking forward to using it.

Thanks!

**Comment by fanningert** [comment]
Here are some examples. In the next days I will add other php-examples for the other exist kirby examples.
http://www.fanninger.at/thomas/works/kirbycms-extension-image

When you need a other example, please tell me and I will add it to this site.

**Comment by bravokiloecho** [comment]
That's brilliant, thanks so much!
